<a href="https://colab.research.google.com/github/DivyaDharshini2293/Deep-Learning/blob/main/BYTS_Neural_Network_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [9]:
y=np.array([[1],[0],[1]])

In [10]:
y

array([[1],
       [0],
       [1]])

In [11]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [18]:
def derivative_sigmoid(x):
  return x*(1-x)

In [14]:
epoch=5000
lr=0.1
input_neuron=x.shape[1]
output_neuron=1
hidden_neuron=3

In [15]:
wh=np.random.uniform(size=(input_neuron,hidden_neuron))
bh=np.random.uniform(size=(1,hidden_neuron))
wo=np.random.uniform(size=(hidden_neuron,output_neuron))
bo=np.random.uniform(size=(1,output_neuron))


In [19]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [20]:
output


array([[0.95548309],
       [0.05844259],
       [0.96859704]])